### ISSUE TITLE
[propagate_const.ctor] Conditional explicit in C++20

### ISSUE THREAD

**Issue by frederick-vs-ja** [cplusplus/fundamentals-ts#82]
LFTS v3 has been rebased onto C++20, so the note in [propagate_const.ctor]/1 is no longer accurate, and we can make use of conditional `explicit` to specify these constructors.

Can we remove the _Note_ and two _Remarks_, and replace _`see below`_ with `explicit(expr)` (also in [propagate_const.overview])?

**Comment by tkoeppe** [comment]
@jwakely: do you think that's sufficiently editorial, covered by the general permission to modernize implied by the rebasing paper?

**Comment by jwakely** [comment]
Yes, I think that makes sense to do as a postscript to that rebase.

In the IS we use `explicit(` _`see below`_ `)` and keep a _Remarks:_ element for the condition, although that's because the conditions are usually non-trivial. For these two constructors it wouldn't be too ugly to use `explicit(!is_convertible_v<U&&, T>)` and remove the _Remarks:_ element.

N.B. `U&&` could be written as simply `U` because `is_convertible<From, To>` is defined in terms of `declval<From>()` which returns `From&&`. So it makes no difference whether you use `U` or `U&&`, it's checking for convertibility from `U&&` to `T` either way.
